# /frontend/nginx-prod.conf
server {
    listen 80;
    server_name dersaadet.seedhr.com.tr;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name dersaadet.seedhr.com.tr;

    ssl_certificate /etc/nginx/ssl/nginx-selfsigned.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx-selfsigned.key;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # API Proxy
    location /upload {
        proxy_pass http://api:8088/upload;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 20M;
    }

    location /job {
        proxy_pass http://api:8088/job;
        proxy_set_header Host $host;
    }

    location /result {
        proxy_pass http://api:8088/result;
        proxy_set_header Host $host;
    }
}
